// Generated by CoffeeScript 1.12.6
(function() {
  var general_query;

  this.create = function(item, success_callback) {
    return general_query(JSON.stringify(item), 'item', 'POST', success_callback);
  };

  this.update = function(item, success_callback) {
    return general_query(JSON.stringify(item), 'item', 'PUT', success_callback);
  };

  this.remove = function(item, success_callback) {
    return general_query(JSON.stringify(item), 'item', 'DELETE', success_callback);
  };

  this.get_item = function(item, success_callback) {
    return general_query(item, 'item', 'GET', success_callback);
  };

  this.get_tags = function(tag_serial, success_callback) {
    return general_query(tag_serial, 'tag', 'GET', success_callback);
  };

  general_query = function(item, urlEndPoint, query_method, success_callback) {
    return browser.storage.local.get(['cnServer', 'cnPort']).then(function(result) {
      var port, server;
      if (result['cnServer'] !== void 0 && result['cnPort'] !== void 0) {
        server = result['cnServer'];
        port = result['cnPort'];
        return $.ajax({
          type: query_method,
          url: 'https://' + server + ':' + port + '/' + urlEndPoint,
          data: item,
          contentType: 'application/json',
          dataType: 'json',
          crossDomain: true,
          crossOrigin: true,
          success: success_callback,
          error: function(request, status) {}
        });
      }
    });
  };

}).call(this);
