// Generated by CoffeeScript 1.12.7
(function() {
  var __CREATE, __FETCH, __REMOVE, __UPDATE, __categoryPath, __itemPath, __portKey, __serverKey, __tagPath, dispatchQuery, generalQuery;

  __serverKey = 'cnServer';

  __portKey = 'cnPort';

  __itemPath = 'item';

  __tagPath = 'tag';

  __categoryPath = 'category';

  __CREATE = 'POST';

  __FETCH = 'GET';

  __UPDATE = 'PUT';

  __REMOVE = 'DELETE';

  this.Status = {
    COMPLETE: 0x0,
    ERROR: 0x1,
    EXCEPTION: 0x2
  };

  this.create = function(payload, success_callback) {
    return dispatchQuery(JSON.stringify(payload), __itemPath, __CREATE, success_callback);
  };

  this.update = function(payload, success_callback) {
    return dispatchQuery(JSON.stringify(payload), __itemPath, __UPDATE, success_callback);
  };

  this.remove = function(payload, success_callback) {
    return dispatchQuery(JSON.stringify(payload), __itemPath, __REMOVE, success_callback);
  };

  this.get_item = function(payload, success_callback) {
    return dispatchQuery(payload, __itemPath, __FETCH, success_callback);
  };

  this.create_category = function(payload, success_callback) {
    return dispatchQuery(JSON.stringify(payload), __categoryPath, __CREATE, success_callback);
  };

  this.get_category = function(success_callback) {
    return dispatchQuery(void 0, __categoryPath, __FETCH, success_callback);
  };

  this.update_category = function(payload, success_callback) {
    return dispatchQuery(JSON.stringify(payload), __categoryPath, __UPDATE, success_callback);
  };

  this.remove_category = function(payload, success_callback) {
    return dispatchQuery(JSON.stringify(payload), __categoryPath, __REMOVE, success_callback);
  };

  this.get_tags = function(tag_serial, success_callback) {
    return dispatchQuery(tag_serial, __tagPath, __FETCH, success_callback);
  };

  dispatchQuery = function(payload, urlEndPoint, query_method, success_callback) {
    if (this.server && this.port) {
      return generalQuery(payload, urlEndPoint, query_method, success_callback, server, port);
    } else if (browser) {
      return browser.storage.local.get([__serverKey, __portKey]).then(function(result) {
        var port, server;
        if (result[__serverKey] !== void 0 && result[__portKey] !== void 0) {
          server = result[__serverKey];
          port = result[__portKey];
          return generalQuery(payload, urlEndPoint, query_method, success_callback, server, port);
        }
      });
    }
  };

  generalQuery = function(payload, urlEndPoint, query_method, success_callback, server, port) {
    return $.ajax({
      type: query_method,
      url: "http://" + server + ":" + port + "/" + urlEndPoint,
      data: payload,
      contentType: 'application/json',
      dataType: 'json',
      crossDomain: true,
      crossOrigin: true,
      success: success_callback
    });
  };

}).call(this);
