// Generated by CoffeeScript 1.12.7
(function() {
  var collectItem, editModal, removeBtnModal, submitBtnModal, tagsInputModal, titleInputModal, urlInputModal;

  titleInputModal = $('#modalInputTitle');

  urlInputModal = $('#modalInputUrl');

  tagsInputModal = $('#modalInputTags');

  removeBtnModal = $('#editModalBtnRemove');

  submitBtnModal = $('#editModalBtnSubmit');

  editModal = $('#editModal');

  editModal.addClass('fade');

  editModal.on('hidden.bs.modal', function() {
    titleInputModal.val('');
    urlInputModal.val('');
    return tagsInputModal.val('');
  });

  this.showEditModal = function(p) {
    var i, spans, tags, tds, title, url;
    getTags(function(result) {
      return new Awesomplete(document.getElementById('modalInputTags'), {
        list: result['object'].map(function(e) {
          return unescape(e.trim());
        }),
        filter: function(text, input) {
          return Awesomplete.FILTER_CONTAINS(text, input.match(/[^,]*$/)[0]);
        },
        item: function(text, input) {
          return Awesomplete.ITEM(text, input.match(/[^,]*$/)[0]);
        },
        replace: function(text) {
          var before;
          before = this.input.value.match(/^.+,\s*|/)[0];
          return this.input.value = before + text + ", ";
        },
        minChars: 1,
        maxItems: 5,
        autoFirst: true
      });
    });
    tds = p.closest('tr').childNodes;
    title = tds[1].childNodes[0].text;
    url = tds[1].childNodes[0].getAttribute('href');
    spans = tds[2].childNodes;
    tags = ((function() {
      var j, ref, results;
      results = [];
      for (i = j = 0, ref = spans.length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        if ($(spans.item(i)).is('span')) {
          results.push($(spans.item(i)).text());
        }
      }
      return results;
    })()).join(', ');
    editModal.modal({
      show: true,
      backdrop: 'static'
    });
    editModal.on('shown.bs.modal', function() {
      var width;
      width = $('#standard').width();
      return tagsInputModal.css('width', width + "px");
    });
    titleInputModal.val(title);
    urlInputModal.val(url);
    return tagsInputModal.val(tags);
  };

  submitBtnModal.click(function() {
    return update(collectItem(), function() {
      return location.reload();
    });
  });

  removeBtnModal.click(function() {
    return remove(collectItem(), function() {
      return location.reload();
    });
  });

  collectItem = function() {
    return {
      name: escape(titleInputModal.val()),
      url: urlInputModal.val(),
      tag: tagsInputModal.val().replace(new RegExp('，', 'g'), ',').split(',').map(function(e) {
        return e.trim();
      }).filter(function(e) {
        return e !== '';
      }).map(function(e) {
        return escape(e);
      }),
      auto_add_tag: true
    };
  };

}).call(this);
