// Generated by CoffeeScript 1.12.7
(function() {
  var bindRowListeners, currentPage, filteredTags, loadItems, packFilterParam, urlObject, urlString;

  currentPage = 0;

  filteredTags = [];

  urlString = window.location.href;

  urlObject = new URL(urlString);

  window.onerror = function(errorMessage, scriptURI, lineNumber, columnNumber, error) {
    $('#errMessage').text(errorMessage);
    $('#errLocation').text(scriptURI + ":" + lineNumber + ":" + columnNumber);
    $('#errObject').text(JSON.stringify(error));
    $('#errorModalBtnSendReport').click(function() {
      return window.open('https://github.com/amastigote/amastigote-browser-ext/issues');
    });
    return $('#errorModal').modal({
      show: true
    });
  };

  this.server = unescape(urlObject.searchParams.get('server'));

  this.port = unescape(urlObject.searchParams.get('port'));

  if (!this.server && !this.port) {
    throw "server or port is not defined in url";
  }

  loadItems = function(payload, container, btnPre, btnSuc, btnFilter, pageIndicator, inputTags) {
    pageIndicator.closest('div').css('visibility', 'hidden');
    return listItems(payload, function(result) {
      var i, item, len, ref;
      if (result['stat'] === Status.COMPLETE) {
        currentPage = result['obj']['currentPage'];
        btnPre.attr('disabled', result['obj']['isFirst']);
        btnSuc.attr('disabled', result['obj']['isLast']);
        pageIndicator.text(currentPage);
        container.empty();
        ref = result['obj']['items'];
        for (i = 0, len = ref.length; i < len; i++) {
          item = ref[i];
          container.append(generateRow(item));
        }
        bindRowListeners(inputTags, btnFilter);
        window.scrollTo(0, 0);
      } else {
        if (result['stat'] === Status.ERROR) {
          btnPre.attr('disabled', true);
          btnSuc.attr('disabled', true);
          container.empty();
          container.append("<tr style='font-size: 15px'><td colspan='4'>无结果</td></tr>");
        }
      }
      return pageIndicator.closest('div').css('visibility', 'visible');
    });
  };

  bindRowListeners = function(inputTags, btnFilter) {
    $('.editHref').click(function(e) {
      e.preventDefault();
      showEditModal(this);
      return false;
    });
    return $('.tagHref').click(function() {
      inputTags.val($(this.childNodes[0]).text());
      return btnFilter.trigger('click');
    });
  };

  packFilterParam = function(rawVal, page) {
    filteredTags = rawVal.replace(/[， 、]/g, ',').split(',').map(function(e) {
      return e.trim();
    }).filter(function(e) {
      return e !== '';
    }).map(function(e) {
      return escape(e);
    });
    return {
      page: page,
      tag: filteredTags
    };
  };

  $(function() {
    var btnClear, btnFilter, btnPre, btnSuc, container, inputTags, pageIndicator;
    container = $('#tableBody');
    btnPre = $('.btnPre');
    btnSuc = $('.btnSuc');
    pageIndicator = $('.pageIndicator');
    btnFilter = $('#btnFilter');
    btnClear = $('#btnClear');
    inputTags = $('#filterByTags');
    $('.form-inline').submit(function(e) {
      e.preventDefault();
      btnFilter.trigger('click');
      return false;
    });
    btnPre.click(function() {
      return loadItems(packFilterParam(filteredTags, currentPage - 2), container, btnPre, btnSuc, btnFilter, pageIndicator, inputTags);
    });
    btnSuc.click(function() {
      return loadItems(packFilterParam(filteredTags, currentPage), container, btnPre, btnSuc, btnFilter, pageIndicator, inputTags);
    });
    btnFilter.click(function() {
      return loadItems(packFilterParam(inputTags.val(), 0), container, btnPre, btnSuc, btnFilter, pageIndicator, inputTags);
    });
    btnClear.click(function() {
      inputTags.val('');
      return btnFilter.trigger('click');
    });
    inputTags.val('');
    loadItems({
      page: 0
    }, container, btnPre, btnSuc, btnFilter, pageIndicator, inputTags);
    return getTags(function(result) {
      var extractLast, split;
      split = function(val) {
        return val.split(/,\s*/);
      };
      extractLast = function(term) {
        return split(term).pop();
      };
      return $('#filterByTags').autocomplete({
        minLength: 1,
        source: function(request, response) {
          return response($.ui.autocomplete.filter(result['obj'].map(function(e) {
            return escapeChars(unescape(e.trim()));
          }), extractLast(request.term)));
        }
      }, {
        focus: function() {
          return false;
        },
        select: function(event, ui) {
          var terms;
          terms = split(this.value);
          terms.pop();
          terms.push(ui.item.value);
          terms.push("");
          this.value = terms.join(", ");
          return false;
        }
      });
    });
  });

  this.escapeChars = function(string) {
    return string.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  };

  this.generateRow = function(item) {
    var tagsBadges;
    tagsBadges = item['tags'].map(function(e) {
      return "<a class='tagHref' href='#'><span class='badge badge-dark' style='font-size: 11px; vertical-align: middle'>" + (escapeChars(unescape(e['name']))) + "</span></a>";
    }).join('&nbsp;');
    return "<tr><td style='vertical-align: middle'>" + item['id'] + "</td><td style='vertical-align: middle; font-weight: bold; font-size: 15px'><a href='" + item['url'] + "'>" + (escapeChars(unescape(item['title']))) + "</a></td><td style='vertical-align: middle'>" + tagsBadges + "</td><td style='font-size: 13px; vertical-align: middle'><a href='#' class='editHref'><i class='fa fa-pencil fa-1'></i>&nbsp;编辑</a></td></tr>";
  };

}).call(this);
