// Generated by CoffeeScript 1.12.7
(function() {
  var generalQuery;

  this.getTags = function(successCallback) {
    return generalQuery(void 0, 'tag', 'GET', successCallback);
  };

  this.listItems = function(payload, successCallback) {
    return generalQuery(payload, 'item/list', 'GET', successCallback);
  };

  this.registerEmail = function(payload, successCallback) {
    return generalQuery(JSON.stringify(payload), 'mail', 'POST', successCallback);
  };

  generalQuery = function(payload, urlEndPoint, queryMethod, successCallback) {
    return $.ajax({
      type: queryMethod,
      url: "http://" + server + ":" + port + "/" + urlEndPoint,
      data: payload,
      contentType: 'application/json',
      dataType: 'json',
      crossDomain: true,
      success: successCallback,
      crossOrigin: true,
      error: function(request, status) {}
    });
  };

}).call(this);
